### ISSUE TITLE
Generating IMU Data

### ISSUE THREAD

**Issue by Zoltan3057** [lukasvst/dm-vio-python-tools#2]
Hi, 
It seems when timestamp is 1650458715596950054, the interpolate_imu_file.py python scrip will read it as float 1.65045872e+18. By casting it to int, get 1650458715596950016.

**Comment by lukasvst** [comment]
Good point, thanks for finding this.
This did not occur on the datasets I have used so far, as their timestamps have probably been double values before.

I will still fix it with the next commit.
