### ISSUE TITLE
cannot run euroc example

### ISSUE THREAD

**Issue by hanskumarKEF** [lukasvst/dm-vio-python-tools#3]
Command: python run_dmvio.py --output=console --dataset=euroc --dmvio_settings=euroc.yaml --withgui --iter=1 --only_seq=0

![image](https://user-images.githubusercontent.com/84034448/174169652-e7b04dcb-4b6a-45a5-a275-01f3040f3ea2.png)

**Comment by lukasvst** [comment]
It looks like the DM-VIO executable does not exist in the build folder. Was the build successful?

Maybe you could try putting absolute paths into the config file.

**Comment by hanskumarKEF** [comment]
absolute paths did the trick! thank you for this great work!
