### ISSUE TITLE
Could not run euroc example

### ISSUE THREAD

**Issue by wwtinwhu** [lukasvst/dm-vio-python-tools#4]
Hello, Lukas @lukasvst ! Thanks for your excellent work!   When I execute run_dmvio.py, the program shutdown because it could not find camera calibration file. 
`Reading Calibration from file ./camera.txt ... not found. Cannot operate without calibration, shutting down.
Segmentation fault (core dumped)`
Meanwhile, I couldn't find this camera file in euroc dataset and dm_vio.

**Comment by lukasvst** [comment]
That's strange, `download_euroc.py` should create the calibration file. Did it (the download script) finish running without errors?

**Comment by wwtinwhu** [comment]
> That's strange, `download_euroc.py` should create the calibration file. Did it (the download script) finish running without errors?

Yes. I use download all command but  I want to test seq0, so  ctrl +c is executed when seq0 is finished. I use download one seq and the calibration file created. And the good news: run successfully! Thanks @lukasvst

**Comment by lukasvst** [comment]
I'm glad the issue could be resolved.

For future reference: The download scripts should not be stopped with ctrl-c, because then not all relevant files will be generated. If you want to download only some sequences, the option `--only_seq` should be used.
